name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        flavor: [all, openai, ai21, local, none]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "${{ matrix.flavor }}" = "none" ]; then
          pip install -e .[test]
        else
          pip install -e .[${{ matrix.flavor }},test]
        fi
    - name: Test with pytest
      run: |
        case "${{ matrix.flavor }}" in
          all)
            pytest tests
            ;;
          local)
            pytest tests/llm_client/local_client
            ;;
          none)
            pytest tests/llm_client/test_llm_client_factory.py
            ;;
          *)
            pytest tests/llm_api_client/${{ matrix.flavor }}_client
            ;;
        esac
